export {
	registryHiveNameSchema,
	registryValueTypeSchema,
	registryValueSchema,
	registryValueInputSchema,
	registryKeySchema,
	registryHiveSchema,
	registrySnapshotSchema,
	registryListRequestSchema,
	registryCreateKeyRequestSchema,
	registryCreateValueRequestSchema,
	registryUpdateKeyRequestSchema,
	registryUpdateValueRequestSchema,
	registryDeleteKeyRequestSchema,
	registryDeleteValueRequestSchema,
	registryCommandRequestSchema,
	registryCommandPayloadSchema,
	registryListResultSchema,
	registryMutationResultSchema,
	registryCommandResponseSchema
} from '../../../../shared/types/registry';

export type {
	RegistryHiveName,
	RegistryValueType,
	RegistryValue,
	RegistryValueInput,
	RegistryKey,
	RegistryHive,
	RegistrySnapshot,
	RegistryListRequest,
	RegistryCreateKeyRequest,
	RegistryCreateValueRequest,
	RegistryUpdateKeyRequest,
	RegistryUpdateValueRequest,
	RegistryDeleteKeyRequest,
	RegistryDeleteValueRequest,
	RegistryCommandRequest,
	RegistryCommandPayload,
	RegistryListResult,
	RegistryMutationResult,
	RegistryCommandResponse,
	RegistryMutationOperationResponse,
	RegistryListOperationResponse
} from '../../../../shared/types/registry';
